# Generated by Django 3.0.6 on 2020-05-10 21:39

import HRM.models
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Users',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('employee_id', models.CharField(max_length=10, unique=True)),
                ('name', models.CharField(max_length=100)),
                ('age', models.PositiveIntegerField()),
                ('ranking', models.FloatField()),
                ('image', models.ImageField(upload_to=HRM.models.Users.upload_photo)),
                ('resume', models.FileField(blank=True, null=True, upload_to=HRM.models.Users.upload_file)),
            ],
        ),
    ]
